controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

messenger-monitor:
    resource: '@SymfonyCastsMessengerMonitorBundle/Resources/config/routing.xml'
    prefix: /_messenger
